version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/apicache"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      pip:
        applies-to: version-updates
        patterns:
        - "*"
    
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      docker-compose:
        applies-to: version-updates
        patterns:
        - "*"

      
  - package-ecosystem: "docker"
    directories:
      - "/apicache"
      - "/screenshotter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      docker:
        applies-to: version-updates
        patterns:
        - "*"  
        
  - package-ecosystem: "npm"
    directories:
      - "/screenshotter"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      npm:
        applies-to: version-updates
        patterns:
        - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "/github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
        - "*"