version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/apicache"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      pip:
        applies-to: version-updates
        
  - package-ecosystem: "npm"
    directories:
      - "/screenshotter"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      npm:
        applies-to: version-updates

  - package-ecosystem: "docker"
    directories:
      - "/apicache"
      - "/screenshotter"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      docker:
        applies-to: version-updates
