version: "3.6"
services:
  app:
    image: livehybrid/dashpub_cacheapi:latest
    environment:
      DASHPUB_HOST: dashpub
      REDIS_HOST: redis-node-0
      REDIS_PASS: TestPassword1
      REDIS_SSL: "False"
      REDIS_USER: dashpub
    stdin_open: true
    tty: true
    links:
      - redis-node-0:redis-node-0
      - dashpub:dashpub
    labels:
      io.rancher.container.pull_image: always
  nginx:
    image: nginx:mainline-perl
    stdin_open: true
    ports:
      - 3001
  dashpub:
    image: livehybrid/splunk-dashpub:latest
    ports:
      - 3000
    environment:
      - DASHPUB_APP=search # This is where our dashboards are located
      - DASHPUB_BRANCH=develop
      - DASHPUB_DASHBOARDS=example[Demo|Example] #dashboardName[Tag1|Tag2],dashboardName2[Tag2,Tag3]
      - REDIS_PASS=TestPassword1
      - DASHPUB_FOLDERNAME=app # Leave this to 'app'
      - DASHPUB_PROJECTNAME=app # Leave this to 'app'
      - NODE_TLS_REJECT_UNAUTHORIZED=0 #This is required to allow dashpub to talk to local Splunk instance with self-signed certs
      - SPLUNKD_TOKEN #Use preset env variable
      - DASHPUB_VERCEL="false" # Do not setup as vercel service
      - SPLUNKD_URL
      - SPLUNKD_USER=admin
    stdin_open: true
    tty: true

  redis-node-0:
    image: docker.io/bitnami/redis-cluster:8.2.0@sha256:77e11f131935d58b37d0e7307ac045860261f6549e3cc40201900d455392200a
    environment:
      REDIS_NODES: redis-node-0
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
