version: "3.6"
services:
  app:
    image: livehybrid/dashpub_cacheapi:latest
    environment:
      DASHPUB_HOST: dashpub
      REDIS_HOST: redis-node-0
      REDIS_PASS: TestPassword1
      REDIS_SSL: "False"
      REDIS_USER: dashpub
    stdin_open: true
    tty: true
    links:
      #      - olly-api:olly_api
      - redis-node-1:redis-node-1
      - redis-node-0:redis-node-0
      - redis-node-2:redis-node-2
      - dashpub:dashpub
    labels:
      io.rancher.container.pull_image: always
  dashpub:
    image: livehybrid/splunk-dashpub:latest
    environment:
      - DASHPUB_APP=search
      - DASHPUB_BRANCH=develop
      - DASHPUB_BUILD_ID="1"
      #      - DASHPUB_CUSTOM_DEPS='[{"@react-google-maps/api"="^2.19.2"},{"react-icons":"*"}]'
      #      - DASHPUB_CUSTOM_VIZ_PATH=/custom_components
      - DASHPUB_DASHBOARDS=example[Demo|Example]
      - DASHPUB_FOLDERNAME=app
      - DASHPUB_FOOTER=Demo Splunk dashboards hosted
      - DASHPUB_HOSTEDBY_NAME=Will Searle
      - DASHPUB_HOSTEDBY_URL=https://www.linkedin.com/in/williamsearle/
      - DASHPUB_PROJECTNAME=app
      - DASHPUB_REPO=https://github.com/livehybrid/dashpub
      - DASHPUB_SCREENSHOTS="true"
      - DASHPUB_SCREENSHOT_DIR=screenshots
      - DASHPUB_SCREENSHOT_EXT=jpg
      - DASHPUB_THEME=dark
      - DASHPUB_TITLE=Demo Dashboards
      - DASHPUB_VERCEL="false"
      - NODE_OPTIONS=--inspect
      - REDIS_PASS=TestPassword1
      - SPLUNKD_HOST=splunk
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SPLUNKD_TOKEN
      - SPLUNKD_URL=https://splunk:8089
      - SPLUNKD_USER=admin
      - VERCEL_URL=localhost
    stdin_open: true
    #volumes:
    #      - /home/rancher/dashboard_publishing_livehybrid/mapping/src/custom_components/:/custom_components
    tty: true
  screenshotter:
    image: livehybrid/dashpub_screenshotter:latest
    environment:
      NGINX_HOST: nginx
      NGINX_PORT: "3001"
    stdin_open: true
    volumes:
      - screenshots:/dashpub/screenshots
    tty: true
  nginx:
    image: nginx:mainline-perl
    stdin_open: true
    labels:
      - traefik.http.routers.dashpub-https.service=dashpub-service
      - traefik.http.services.dashpub-service.loadbalancer.server.port=3001
      - traefik.http.routers.dashpub-https.rule=Host(`dashpub.mac.splunk.engineer`)
      - traefik.http.routers.dashpub-https.entrypoints=https
      - traefik.http.routers.dashpub-https.tls=true
    ports:
      - 3001
    volumes:
      - screenshots:/var/www/html/public/screenshots
      - screenshots:/var/www/html/public/screens
    tty: true
    # logging:
    #   driver: splunk
    #   options:
    #     splunk-format: raw
    #     splunk-index: nginx_web
    #     splunk-source: docker:dashpub:nginx
    #     splunk-sourcetype: nginx:plus:access
    #     splunk-token: REDACTED
    #     splunk-url: REDACTED
    #     splunk-verify-connection: "false"

  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.2.5@sha256:1212402afa3f991a27322e3d7540acf6d56b13497311d4364e1bfc2c1b34884b
    environment:
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.2.5@sha256:1212402afa3f991a27322e3d7540acf6d56b13497311d4364e1bfc2c1b34884b
    environment:
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.2.5@sha256:1212402afa3f991a27322e3d7540acf6d56b13497311d4364e1bfc2c1b34884b
    environment:
      REDISCLI_AUTH: TestPassword1
      REDIS_CLUSTER_CREATOR: "yes"
      REDIS_CLUSTER_REPLICAS: "0"
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
    links:
      - redis-node-1:redis-node-1
      - redis-node-0:redis-node-0
    labels:
      io.rancher.container.pull_image: always

volumes:
  screenshots:
    external: false
