version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.2.5
    environment:
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  app:
    image: livehybrid/dashpub_cacheapi:latest
    environment:
      DASHPUB_HOST: dashpub
      REDIS_HOST: redis-node-0
      REDIS_PASS: TestPassword1
      REDIS_SSL: 'False'
      REDIS_USER: dashpub
    stdin_open: true
    tty: true
    links:
    - olly-api:olly_api
    - redis-node-1:redis-node-1
    - redis-node-0:redis-node-0
    - redis-node-2:redis-node-2
    - dashpub:dashpub
    labels:
      io.rancher.container.pull_image: always
  dashpub:
    image: livehybrid/splunk-dashpub:latest
    environment:
      DASHPUB_APP: etyd
      DASHPUB_BRANCH: develop
      DASHPUB_BUILD_ID: '1'
      DASHPUB_CUSTOM_DEPS: '[{"@react-google-maps/api": "^2.19.2"},{"react-icons":"*"}]'
      DASHPUB_CUSTOM_VIZ_PATH: /custom_components
      DASHPUB_DASHBOARDS: 1000k_in_2024[Running],tesla_telemetry[Demo|Tesla],highlevel[Demo|Monitoring],octopus_energy_usage[Monitoring|Energy],equine_energy_usage[Demo|Energy|Monitoring],o11y_sample_charts[Demo|Observability|O11y],engenie_chargers_2[Demo|Energy],example[Demo]
      DASHPUB_FOLDERNAME: app
      DASHPUB_FOOTER: Demo Splunk dashboards hosted
      DASHPUB_HOSTEDBY_NAME: Will Searle
      DASHPUB_HOSTEDBY_URL: https://www.linkedin.com/in/williamsearle/
      DASHPUB_PROJECTNAME: app
      DASHPUB_REPO: https://github.com/livehybrid/dashpub
      DASHPUB_SCREENSHOTS: 'true'
      DASHPUB_SCREENSHOT_DIR: screenshots
      DASHPUB_SCREENSHOT_EXT: jpg
      DASHPUB_THEME: dark
      DASHPUB_TITLE: Demo Dashboards
      DASHPUB_VERCEL: 'false'
      NODE_OPTIONS: --inspect
      REDIS_PASS: TestPassword1
      SPLUNKD_HOST: 192.168.0.222
      SPLUNKD_TOKEN: REDACTED
      SPLUNKD_URL: REDACTED
      SPLUNKD_USER: REDACTED
      VERCEL_URL: dashboards.splunk.engineer
    stdin_open: true
    volumes:
    - /home/rancher/dashboard_publishing_livehybrid/mapping/src/custom_components/:/custom_components
    tty: true
  screenshotter:
    image: livehybrid/dashpub_screenshotter:latest
    environment:
      NGINX_HOST: nginx
      NGINX_PORT: '3001'
    stdin_open: true
    volumes:
    - screenshots:/dashpub/screenshots
    tty: true
  nginx:
    image: nginx:latest
    stdin_open: true
    volumes:
    - /home/rancher/dashpub-plus/nginx/public.conf:/etc/nginx/conf.d/public.conf
    - screenshots:/var/www/html/public/screenshots
    - screenshots:/var/www/html/public/screens
    tty: true
    logging:
      driver: splunk
      options:
        splunk-format: raw
        splunk-index: nginx_web
        splunk-source: docker:dashpub:nginx
        splunk-sourcetype: nginx:plus:access
        splunk-token: REDACTED
        splunk-url: REDACTED
        splunk-verify-connection: 'false'
  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.2.5
    environment:
      REDISCLI_AUTH: TestPassword1
      REDIS_CLUSTER_CREATOR: 'yes'
      REDIS_CLUSTER_REPLICAS: '0'
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
    links:
    - redis-node-1:redis-node-1
    - redis-node-0:redis-node-0
    labels:
      io.rancher.container.pull_image: always
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.2.5
    environment:
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2
      REDIS_PASSWORD: TestPassword1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always

